# Generated by Django 6.0.5 on 2026-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_courseclass_classmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5')], default='', max_length=10),
        ),
    ]
