# Generated by Django 6.0.5 on 2026-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_department_assignment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='input_format',
            field=models.TextField(blank=True, default='', help_text='Describe how input should be read e.g. "First line is the name, second line is the score"'),
        ),
    ]
