# Generated by Django 6.0.5 on 2026-06-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_courseclass_classmembership'),
        ('assignments', '0003_assignment_input_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.courseclass'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='input_format',
            field=models.TextField(blank=True, default=''),
        ),
    ]
