# Generated by Django 6.0.5 on 2026-06-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_courseclass_department_courseclass_year'),
        ('assignments', '0004_assignment_course_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.courseclass'),
            preserve_default=False,
        ),
    ]
